### ISSUE TITLE
Error (Astro) in Version script_0.1.1.js

### ISSUE THREAD

**Issue by ManuZz80** [Schmakus/ioBroker.LightOnOffPresence#1]
Ich habe die Script Version v 0.1.0 BETA bisher genutzt und nun auf die aktuelle geupdated, wie gefordert nur den Teil unter dem Block mit //     AB HIER NICHTS MEHR ÄNDERN           // 

Nach dem Starten des scripts bekomme ich folgende Fehler: 

Interessant ist auch das ich kein einziges deconz Gerät, bzw Stick angeschlossen oder eingerichtet habe. Ich habe auch nicht herausgefunden woher das kommt. 

Muss ich für die AstroZeit vielleicht noch was installieren? 

27.3.2021, 09:02:09.846	[info ]: javascript.0 (791) Stop script script.js.test_flur
27.3.2021, 09:02:10.899	[info ]: javascript.0 (791) Start javascript script.js.test_flur
27.3.2021, 09:02:10.938	[info ]: javascript.0 (791) script.js.test_flur: subscribe: {"pattern":{"id":"deconz.1.Lights.2.hue","ack":false,"change":"any","q":0},"name":"script.js.test_flur"}
27.3.2021, 09:02:10.941	[info ]: javascript.0 (791) script.js.test_flur: registered 1 subscription and 0 schedules
27.3.2021, 09:02:10.947	[error]: javascript.0 (791) script.js.test_flur: TypeError: Cannot read property 'replace' of undefined
27.3.2021, 09:02:10.948	[error]: javascript.0 (791)     at getTimeInfoFromAstroString (script.js.test_flur:845:19)
27.3.2021, 09:02:10.948	[error]: javascript.0 (791)     at script.js.test_flur:289:13
27.3.2021, 09:02:10.949	[error]: javascript.0 (791)     at script.js.test_flur:954:3

**Comment by Schmakus** [comment]
Zeig mal deine Zeitpläne. Und aktiviere das gesamte Logging.
Und was ist das für ein Trigger auf "deconz.1.Lights.2.hue" ? Hast du noch weiteren Code eingefügt?

**Comment by ManuZz80** [comment]
Nein, ich habe nichts eingefügt, ich habe keine Ahnung woher das kommt, ich habe den broker auch neu aufgesetzt, nachdem ich meinen deconz stick ausgetauscht habe. Deine Trigger habe ich alle entfernt, selbst hatte ich damals nur deconz.0.* trigger. 
Kann das sein das die Astrofunktion des Scriptes auf die Astrofunktion des deconz zugreift?

Meine Zeitpläne (ich benutze nur 1 und 2) -->

//------------------------------------------------------//
//    Hier die Zeitpläne der Lampen anlegen             //
//------------------------------------------------------//
let arrSchedules = {
    // Zeitplan 1
	1: {from: '08:00', to: '22:00', days: '1-7', brightness: 55, colorTemp: 360, color: '', state: true, name:"Tagsüber von 8-22 Uhr: Helligkeit 50" },
	// Zeitplan 2
	2: {from: '22:00', to: '08:00', days: '1-7', brightness: 20, colorTemp: 360, color: '', state: true, name:"Nachts von 22-8 Uhr Helligkeit 5"},
	// Zeitplan 3
	3: {from: '05:00', to: '22:00', days: '1-7', brightness: 70, colorTemp: 360, color: '', state: true, name:"Tagsüber von 5-22 Uhr: Helligkeit 70"},
	// Zeitplan 4
	4: {from: '22:00', to: '06:00', days: '1-7', brightness: 0, colorTemp: 360, color: '', state: false, name:"Nachts von 22 - 6 Uhr AUS"},
    // Zeitplan 5
    5: {from: '06:00', to: '21:30', days: '1-7', brightness: 80, colorTemp: 300, color: '', state: true, name:"Nachts von 22-8 Uhr Helligkeit 80"},
    // Zeitplan 6
    6: {from: '21:30', to: '06:00', days: '1-7', brightness: 10, colorTemp: 360, color: '', state: true, name:"Nachts von 21:30-6 Uhr Helligkeit 10"}
};
// Astrozeiten
// sunrise', 'sunset', 'sunriseEnd', 'sunsetStart', 'dawn', 'dusk', 'nauticalDawn', 'nauticalDusk', 'nightEnd', 'night', 'goldenHourEnd', 'goldenHour'

// Astrozeiten mit Offset in Minuten
// sunrise+30', 'sunset-30', 'sunriseEnd', 'sunsetStart', 'dawn', 'dusk', 'nauticalDawn', 'nauticalDusk', 'nightEnd', 'night', 'goldenHourEnd', 'goldenHour'


Das log mit aktiviertem debug, beim auslösen des BWM kommt leider nicht mehr. 

07:30:36.745	info	javascript.0 (791) Start javascript script.js.test_flur
07:30:36.778	info	javascript.0 (791) script.js.test_flur: subscribe: {"pattern":{"id":"deconz.1.Lights.2.hue","ack":false,"change":"any","q":0},"name":"script.js.test_flur"}
07:30:36.780	info	javascript.0 (791) script.js.test_flur: registered 1 subscription and 0 schedules
07:30:36.783	error	javascript.0 (791) script.js.test_flur: TypeError: Cannot read property 'replace' of undefined
07:30:36.784	error	javascript.0 (791) at getTimeInfoFromAstroString (script.js.test_flur:845:19)
07:30:36.785	error	javascript.0 (791) at script.js.test_flur:289:13
07:30:36.785	error	javascript.0 (791) at script.js.test_flur:954:3

**Comment by Schmakus** [comment]
Hi, ich kann den Fehler nicht reproduzieren. Welche Versionen hast du vom js-controller?
Ist das der gesamte Log?
Zeig noch deine Geräte und Lampen.

**Comment by Schmakus** [comment]
.....Jetzt komm ich drauf. Mein Fehler.
Du musst bei deinen Zeitplänen folgendes Umbenennen:
"from" => "start"
"to" => "end"

**Comment by ManuZz80** [comment]
Ich hab die Version 5.0.14 laufen, also die aktuellste. 
Hier die Räume und Lampen, genau wie im laufenden script:


//    Hier die Gruppen/Räume anlegen        //
//------------------------------------------//
let arrGroups = [
        //Flur
    {
        description: 'Flur',                                    //Beschreibung der Gruppe. Notwendig zur Erzeugung der Datenpunkte
        pathOn: ['zigbee.0.00158d000464fca4.click', 'zigbee.0.00158d000464fcf5.click'],     //Pfad zum Taster für Licht ein
        pathOff: ['zigbee.0.00158d000464fca4.double_click', 'zigbee.0.00158d000464fcf5.double_click'],     //Pfad zum Taster für Licht aus
        pathDimmUp: [],  //Pfad zum Taster für Hochdimmen !!! Aktuell nur Homematic
        pathDimmDown: [], //Pfad zum Taster für Runterdimmen !!! Aktuell nur Homematic
        pathBWM: ['zigbee.0.ec1bbdfffe79d3c8.occupancy', 'zigbee.0.ec1bbdfffeb4d7d0.occupancy'],       //Pfad zum Bewegungsmelder
        pathLux: 'zigbee.0.04cf8cdf3c78ae7c.illuminance',       //Pfad zum Lichtsensor in Lux
        timerMotion: 20,                                        // Sekunden: Zeit, nachder das Licht ausgeschaltet wird, sofern keine Bewegung mehr erkannt wird.
        timerSwitch: 3600,                                      // Sekunden >0: Licht wird automatisch ausgeschaltet, sofern keine Bewegung mehr erkannt wird (Rückfallebene) 
        lights: [1],                                            // Leuchten, welche zur Gruppe gehören
        lockBWM: false,                                          // Sperre für Bewegungsmelder, wenn das Licht manuell per Taster oder Datenpunkt eingeschaltet wurde
        defaultSwitch: false,                                    // true: Lampen werden mit Schalter auf Default Helligkeit gesetzt // false: Lampen werden nach Zeitplan gesetzt
        keyStrokes: 1,                                          // 1 = Nur ein Tastendruck EIN wird gewertet. >1 = Es werden entsprechend der Zahlt gewertet
    },
    //Ankleide
    /*
    {
        description: 'Ankleide',                                //Beschreibung der Gruppe. Notwendig zur Erzeugung der Datenpunkte
        pathOn: ['hm-rpc.1.00171A499D4685.11.PRESS_SHORT'],     //Pfad zum Taster für Licht ein
        pathOff: ['hm-rpc.1.00171A499D4685.12.PRESS_SHORT', 'hm-rpc.1.00171A499D4685.16.PRESS_SHORT'],    //Pfad zum Taster für Licht aus
        pathDimmUp: ['hm-rpc.1.00171A499D4685.11.PRESS_LONG'],  //Pfad zum Taster für Hochdimmen !!! Aktuell nur Homematic
        pathDimmDown: ['hm-rpc.1.00171A499D4685.12.PRESS_LONG'],//Pfad zum Taster für Runterdimmen !!! Aktuell nur Homematic
        pathBWM: [],                                            //Pfad zum Bewegungsmelder
        pathLux: '',                                            //Pfad zum Lichtsensor in Lux
        timerMotion: 10,                                        // Sekunden: Zeit, nachder das Licht ausgeschaltet wird, sofern keine Bewegung mehr erkannt wird.
        timerSwitch: 3600,                                      // Sekunden >0: Licht wird automatisch ausgeschaltet, sofern keine Bewegung mehr erkannt wird (Rückfallebene) 
        lights: [2],                                            // Leuchten, welche zur Gruppe gehören
        lockBWM: true,                                          // Sperre für Bewegungsmelder, wenn das Licht manuell per Taster oder Datenpunkt eingeschaltet wurde
        defaultSwitch: false,                                   // true: Lampen werden mit Schalter auf Default Helligkeit gesetzt // false: Lampen werden nach Zeitplan gesetzt
        keyStrokes: 1,                                          // 1 = Nur ein Tastendruck EIN wird gewertet. >1 = Es werden entsprechend der Zahlt gewertet
    },
    //Schlafzimmer
    {
        description: 'Schlafzimmer',                            //Beschreibung der Gruppe. Notwendig zur Erzeugung der Datenpunkte
        pathOn: ['hm-rpc.1.00171A499D4685.15.PRESS_SHORT'],     //Pfad zum Taster für Licht ein
        pathOff: ['hm-rpc.1.00171A499D4685.16.PRESS_SHORT'],    //Pfad zum Taster für Licht aus
        pathDimmUp: ['hm-rpc.1.00171A499D4685.15.PRESS_LONG'],  //Pfad zum Taster für Hochdimmen !!! Aktuell nur Homematic
        pathDimmDown: ['hm-rpc.1.00171A499D4685.16.PRESS_LONG'],//Pfad zum Taster für Runterdimmen !!! Aktuell nur Homematic
        pathBWM: [],                                            //Pfad zum Bewegungsmelder
        pathLux: '',                                            //Pfad zum Lichtsensor in Lux
        timerMotion: 10,                                        // Sekunden: Zeit, nachder das Licht ausgeschaltet wird, sofern keine Bewegung mehr erkannt wird.
        timerSwitch: 3600,                                      // Sekunden >0: Licht wird automatisch ausgeschaltet, sofern keine Bewegung mehr erkannt wird (Rückfallebene) 
        lights: [3],                                            // Leuchten, welche zur Gruppe gehören
        lockBWM: true,                                          // Sperre für Bewegungsmelder, wenn das Licht manuell per Taster oder Datenpunkt eingeschaltet wurde
        defaultSwitch: false,                                   // true: Lampen werden mit Schalter auf Default Helligkeit gesetzt // false: Lampen werden nach Zeitplan gesetzt
        keyStrokes: 1,                                          // 1 = Nur ein Tastendruck EIN wird gewertet. >1 = Es werden entsprechend der Zahlt gewertet
    },
    //Wohnzimmer Spots
    {
        description: 'Wohnzimmer Spots',                         //Beschreibung der Gruppe. Notwendig zur Erzeugung der Datenpunkte
        pathOn: ['hm-rpc.1.00171A499D46DC.14.PRESS_SHORT'],     //Pfad zum Taster für Licht ein
        pathOff: ['hm-rpc.1.00171A499D46DC.15.PRESS_SHORT'],    //Pfad zum Taster für Licht aus
        pathDimmUp: ['hm-rpc.1.00171A499D46DC.14.PRESS_LONG'],  //Pfad zum Taster für Hochdimmen !!! Aktuell nur Homematic
        pathDimmDown: ['hm-rpc.1.00171A499D46DC.15.PRESS_LONG'],//Pfad zum Taster für Runterdimmen !!! Aktuell nur Homematic
        pathBWM: [],                                            //Pfad zum Bewegungsmelder
        pathLux: '',                                            //Pfad zum Lichtsensor in Lux
        timerMotion: 10,                                        // Sekunden: Zeit, nachder das Licht ausgeschaltet wird, sofern keine Bewegung mehr erkannt wird.
        timerSwitch: 3600,                                      // Sekunden >0: Licht wird automatisch ausgeschaltet, sofern keine Bewegung mehr erkannt wird (Rückfallebene) 
        lights: [5],                                            // Leuchten, welche zur Gruppe gehören
        lockBWM: true,                                          // Sperre für Bewegungsmelder, wenn das Licht manuell per Taster oder Datenpunkt eingeschaltet wurde
        defaultSwitch: false,                                   // true: Lampen werden mit Schalter auf Default Helligkeit gesetzt // false: Lampen werden nach Zeitplan gesetzt
        keyStrokes: 1,                                          // 1 = Nur ein Tastendruck EIN wird gewertet. >1 = Es werden entsprechend der Zahlt gewertet
    }
    */
];

//------------------------------------------------------//
//    Hier die Lampen oder Lampengruppen anlegen        //
//------------------------------------------------------//
let arrLights = {
    1: {
        name: 'Flur Licht',                                     // Bezeichnung der Leuchte
        pathControl: 'zigbee.0.group_1.brightness',                 // Pfad zum Datenpunkt, mit dem die Lampe geschaltet wird. (Brightness oder State)
        pathColortemp: 'zigbee.0.group_1.colortemp',                  // Pfad zum Datenpunkt, mit dem die Farbtemperatur vorgegeben wird. - sofern vorhanden
        pathTransistion: 'zigbee.0.group_1.transition_time',    // Pfad zum Datenpunkt, für die Transition Time.
        pathColor: '',                                          // Pfad zum Datenpunkt, für die Farbe. - sofern vorhanden
        defaultLevel: 55,                                       // Default Level-Wert beim Einschalten, sollte kein Zeitplan zutreffen
        defaultColorTemp: 251,                                  // Sofern ein Wert gesetzt ist, Farbtemperatur - sofern vorhanden
        color: '',                                              // Sofern ein Wert gesetzt ist, wird die Lampe entsprechend farbig. - sofern vorhanden
        schedules: [1,2],                                       // Zeitplan-Zuordnung, wann die Leuchte mit welcher Helligkeit leuchtet
        buttonPress: 1,                                         // Bei welchem Tastendruck soll die Lampe reagieren? (Nur rellevant wenn keystrokes > 1)
        emergencyLevel: 50,                                     // Level > 0: Das Licht wird Auslösen des Emergency Datenpunkts auf das eingestellte Level geschaltet
    },
    /*
    2: {
        name: 'Ankleide Spots',
        pathControl: '',                // Pfad zum Datenpunkt, mitdem die Lampe geschaltet wird. (Brightness oder State)
        pathColortemp: '',                 // Pfad zum Datenpunkt, mitdem die Lampe geschaltet wird. (Brightness oder State) - sofern vorhanden
        pathTransistion: '',   // Pfad zum Datenpunkt, für die Transition Time.
        pathColor: '',                                          // Pfad zum Datenpunkt, für die Farbe. - sofern vorhanden
        defaultLevel: 70,                                       // Default Level-Wert beim Einschalten, sollte kein Zeitplan zutreffen
        defaultColorTemp: 370,                                  // Sofern ein Wert gesetzt ist, Farbtemperatur - sofern vorhanden
        color: '',                                              // Sofern ein Wert gesetzt ist, wird die Lampe entsprechend farbig. - sofern vorhanden
        schedules: [1,2],                                       // Zeitplan-Zuordnung, wann die Leuchte mit welcher Helligkeit leuchtet
        buttonPress: 1,                                         // Bei welchem Tastendruck soll die Lampe reagieren?
        emergencyLevel: 100,                                    // Level > 0: Das Licht wird Auslösen des Emergency Datenpunkts auf das eingestellte Level geschaltet    
    },
    3: {
        name: 'Schlafzimmer Spots',
        pathControl: '',                // Pfad zum Datenpunkt, mitdem die Lampe geschaltet wird. (Brightness oder State)
        pathColortemp: '',                 // Pfad zum Datenpunkt, mitdem die Lampe geschaltet wird. (Brightness oder State) - sofern vorhanden
        pathTransistion: '',   // Pfad zum Datenpunkt, für die Transition Time.
        pathColor: '',                                          // Pfad zum Datenpunkt, für die Farbe. - sofern vorhanden
        defaultLevel: 70,                                       // Default Level-Wert beim Einschalten, sollte kein Zeitplan zutreffen
        defaultColorTemp: 370,                                  // Sofern ein Wert gesetzt ist, Farbtemperatur - sofern vorhanden
        color: '',                                              // Sofern ein Wert gesetzt ist, wird die Lampe entsprechend farbig. - sofern vorhanden
        schedules: [1,2],                                       // Zeitplan-Zuordnung, wann die Leuchte mit welcher Helligkeit leuchtet
        buttonPress: 1,                                         // Bei welchem Tastendruck soll die Lampe reagieren?
        emergencyLevel: 100,                                    // Level > 0: Das Licht wird Auslösen des Emergency Datenpunkts auf das eingestellte Level geschaltet    
    },
    4: {
        name: 'Küche Spots',
        pathControl: '',             // Pfad zum Datenpunkt, mitdem die Lampe geschaltet wird. (Brightness oder State)
        pathColortemp: '',            // Pfad zum Datenpunkt, mitdem die Lampe geschaltet wird. (Brightness oder State) - sofern vorhanden
        pathTransistion: '',    // Pfad zum Datenpunkt, für die Transition Time.
        pathColor: '',                                          // Pfad zum Datenpunkt, für die Farbe. - sofern vorhanden
        defaultLevel: 70,                                       // Default Level-Wert beim Einschalten, sollte kein Zeitplan zutreffen
        defaultColorTemp: 370,                                  // Sofern ein Wert gesetzt ist, Farbtemperatur - sofern vorhanden
        defaultColor: '',                                       // Sofern ein Wert gesetzt ist, wird die Lampe entsprechend farbig. - sofern vorhanden
        schedules: [3],                                         // Zeitplan-Zuordnung, wann die Leuchte mit welcher Helligkeit leuchtet
        buttonPress: [1],                                       // Bei welchem Tastendruck soll die Lampe reagieren?
        emergencyLevel: 100,                                    // Level > 0: Das Licht wird Auslösen des Emergency Datenpunkts auf das eingestellte Level geschaltet   
    },
    5: {
        name: 'Wohnzimmer Spots',
        pathControl: '',                // Pfad zum Datenpunkt, mitdem die Lampe geschaltet wird. (Brightness oder State)
        pathColortemp: '',                 // Pfad zum Datenpunkt, mitdem die Lampe geschaltet wird. (Brightness oder State) - sofern vorhanden
        pathTransistion: '',   // Pfad zum Datenpunkt, für die Transition Time.
        pathColor: '',                     // Pfad zum Datenpunkt, für die Farbe. - sofern vorhanden
        defaultLevel: 70,                                       // Default Level-Wert beim Einschalten, sollte kein Zeitplan zutreffen
        defaultColorTemp: 370,                                  // Sofern ein Wert gesetzt ist, Farbtemperatur - sofern vorhanden
        color: '0',                                              // Sofern ein Wert gesetzt ist, wird die Lampe entsprechend farbig. - sofern vorhanden
        schedules: [5,6],                                       // Zeitplan-Zuordnung, wann die Leuchte mit welcher Helligkeit leuchtet
        buttonPress: 1,                                         // Bei welchem Tastendruck soll die Lampe reagieren?
        emergencyLevel: 100,                                    // Level > 0: Das Licht wird Auslösen des Emergency Datenpunkts auf das eingestellte Level geschaltet    
    }
    */
};

//------------------------------------------------------//
//    Hier die Zeitpläne der Lampen anlegen             //

**Comment by ManuZz80** [comment]
Easy :) hab ich geändert, nun keine Fehler mehr :) danke dir!
