### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by Ricox1975** [Schmakus/ioBroker.LightOnOffPresence#2]
Script zeigt folgende Fehler:

![Script error BWM](https://user-images.githubusercontent.com/52467622/128608835-7613bd0c-1408-4fb8-b0f8-86e483c0a43a.JPG)

**Comment by Schmakus** [comment]
Hi,
welcher JS-Controller, JavaScript Adapter Version?

Zeig mal, wie du deine Einstellungen im Script aussehen. 
So wie es aussieht, fehlen bei dir die eckigen Klammern bei den Pfaden "pathOn".

pathOn: **[**'hm-rpc.1.00171A499D46DC.32.PRESS_SHORT'**]**,

**Comment by Ricox1975** [comment]
Moin,
gelöst, eine eckige Klammer hat gefehlt. 

danke

Info: JS 3.3.15 Java 5.2.8
